-- Admin-managed, database-authoritative promotions. All campaign rules and
-- redemption records remain private; Customers interact only through guarded RPCs.

CREATE TABLE private.promotion_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  discount_type TEXT NOT NULL CHECK (discount_type IN ('fixed', 'percentage')),
  discount_value NUMERIC(10,2) NOT NULL CHECK (discount_value > 0),
  minimum_subtotal NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (minimum_subtotal >= 0),
  maximum_discount NUMERIC(10,2) CHECK (maximum_discount IS NULL OR maximum_discount > 0),
  total_budget NUMERIC(12,2) CHECK (total_budget IS NULL OR total_budget > 0),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL CHECK (ends_at > starts_at),
  service_date_start DATE,
  service_date_end DATE,
  is_active BOOLEAN NOT NULL DEFAULT false,
  first_order_only BOOLEAN NOT NULL DEFAULT false,
  per_user_limit INTEGER NOT NULL DEFAULT 1 CHECK (per_user_limit BETWEEN 1 AND 100),
  eligible_meal_types TEXT[] NOT NULL DEFAULT ARRAY['breakfast','lunch','dinner']::TEXT[],
  eligible_meal_ids UUID[] NOT NULL DEFAULT ARRAY[]::UUID[],
  eligible_zone_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  created_by UUID NOT NULL REFERENCES auth.users(id),
  updated_by UUID NOT NULL REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT promotion_code_format CHECK (code = upper(code) AND code ~ '^[A-Z0-9][A-Z0-9_-]{2,29}$'),
  CONSTRAINT promotion_percentage_value CHECK (discount_type <> 'percentage' OR discount_value <= 100),
  CONSTRAINT promotion_service_dates CHECK (service_date_start IS NULL OR service_date_end IS NULL OR service_date_end >= service_date_start),
  CONSTRAINT promotion_meal_types CHECK (
    cardinality(eligible_meal_types) > 0
    AND eligible_meal_types <@ ARRAY['breakfast','lunch','dinner']::TEXT[]
  )
);

CREATE TABLE private.promotion_redemptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  promotion_id UUID NOT NULL REFERENCES private.promotion_campaigns(id) ON DELETE RESTRICT,
  order_id UUID NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE RESTRICT,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  discount_amount NUMERIC(10,2) NOT NULL CHECK (discount_amount > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE private.promotion_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promotion_id UUID,
  actor_id UUID NOT NULL REFERENCES auth.users(id),
  action TEXT NOT NULL CHECK (action IN ('created','updated','activated','paused','deleted')),
  snapshot JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX promotion_campaigns_active_window_idx ON private.promotion_campaigns(is_active, starts_at, ends_at);
CREATE INDEX promotion_redemptions_campaign_idx ON private.promotion_redemptions(promotion_id, created_at);
CREATE INDEX promotion_redemptions_user_idx ON private.promotion_redemptions(promotion_id, user_id);

ALTER TABLE public.orders
  ADD COLUMN promotion_id UUID REFERENCES private.promotion_campaigns(id) ON DELETE SET NULL,
  ADD COLUMN promotion_code_snapshot TEXT,
  ADD COLUMN promotion_name_snapshot TEXT;

CREATE OR REPLACE FUNCTION private.promotion_evaluation(
  p_campaign_id UUID,
  p_user_id UUID,
  p_order_date DATE,
  p_meal_type TEXT,
  p_zone_id TEXT,
  p_meal_id UUID,
  p_eligible_subtotal NUMERIC,
  p_at TIMESTAMPTZ DEFAULT clock_timestamp(),
  p_lock BOOLEAN DEFAULT false
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  campaign private.promotion_campaigns%ROWTYPE;
  used_count BIGINT;
  spent NUMERIC(12,2);
  amount NUMERIC(10,2);
BEGIN
  IF p_lock THEN
    SELECT * INTO campaign FROM private.promotion_campaigns WHERE id = p_campaign_id FOR UPDATE;
  ELSE
    SELECT * INTO campaign FROM private.promotion_campaigns WHERE id = p_campaign_id;
  END IF;
  IF NOT FOUND THEN RETURN jsonb_build_object('eligible',false,'reason','Offer not found.'); END IF;
  IF NOT campaign.is_active THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is currently paused.'); END IF;
  IF p_at < campaign.starts_at THEN RETURN jsonb_build_object('eligible',false,'reason','This offer has not started yet.'); END IF;
  IF p_at >= campaign.ends_at THEN RETURN jsonb_build_object('eligible',false,'reason','This offer has expired.'); END IF;
  IF p_eligible_subtotal < campaign.minimum_subtotal THEN
    RETURN jsonb_build_object('eligible',false,'reason',format('Add ₹%s more eligible food value to use this offer.', campaign.minimum_subtotal - p_eligible_subtotal));
  END IF;
  IF NOT p_meal_type = ANY(campaign.eligible_meal_types) THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is not available for the selected meal service.'); END IF;
  IF cardinality(campaign.eligible_meal_ids) > 0 AND NOT p_meal_id = ANY(campaign.eligible_meal_ids) THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is not available for the selected meal.'); END IF;
  IF cardinality(campaign.eligible_zone_ids) > 0 AND NOT p_zone_id = ANY(campaign.eligible_zone_ids) THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is not available at this delivery address.'); END IF;
  IF campaign.service_date_start IS NOT NULL AND p_order_date < campaign.service_date_start THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is not available for the selected date.'); END IF;
  IF campaign.service_date_end IS NOT NULL AND p_order_date > campaign.service_date_end THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is not available for the selected date.'); END IF;
  IF campaign.first_order_only AND EXISTS (
    SELECT 1 FROM public.orders o WHERE o.user_id = p_user_id AND o.status <> 'cancelled'
  ) THEN RETURN jsonb_build_object('eligible',false,'reason','This offer is only for your first completed order.'); END IF;
  SELECT count(*) INTO used_count FROM private.promotion_redemptions r
  WHERE r.promotion_id = campaign.id AND r.user_id = p_user_id;
  IF used_count >= campaign.per_user_limit THEN RETURN jsonb_build_object('eligible',false,'reason','You have already used this offer.'); END IF;

  amount := CASE campaign.discount_type
    WHEN 'percentage' THEN round(p_eligible_subtotal * campaign.discount_value / 100, 2)
    ELSE campaign.discount_value
  END;
  IF campaign.maximum_discount IS NOT NULL THEN amount := least(amount, campaign.maximum_discount); END IF;
  amount := least(amount, p_eligible_subtotal);
  IF amount <= 0 THEN RETURN jsonb_build_object('eligible',false,'reason','This offer does not apply to the selected order.'); END IF;

  SELECT coalesce(sum(r.discount_amount),0) INTO spent FROM private.promotion_redemptions r WHERE r.promotion_id = campaign.id;
  IF campaign.total_budget IS NOT NULL AND spent + amount > campaign.total_budget THEN
    RETURN jsonb_build_object('eligible',false,'reason','This offer has reached its campaign limit.');
  END IF;
  RETURN jsonb_build_object(
    'eligible',true,'id',campaign.id,'code',campaign.code,'name',campaign.name,
    'description',campaign.description,'discount_amount',amount,
    'minimum_subtotal',campaign.minimum_subtotal,'ends_at',campaign.ends_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_order_promotion_quote(
  p_order_date DATE,
  p_meal_type TEXT,
  p_address_id UUID,
  p_meal_id UUID,
  p_quantity INTEGER,
  p_customizations JSONB DEFAULT '[]',
  p_promotion_code TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  u UUID := auth.uid();
  meal public.meals%ROWTYPE;
  menu_day public.menu_days%ROWTYPE;
  menu_item public.menu_items%ROWTYPE;
  address public.addresses%ROWTYPE;
  zone public.delivery_zones%ROWTYPE;
  customization public.meal_customizations%ROWTYPE;
  campaign private.promotion_campaigns%ROWTYPE;
  entry JSONB;
  evaluation JSONB;
  available JSONB := '[]'::JSONB;
  applied JSONB := NULL;
  normalized_code TEXT := nullif(upper(btrim(coalesce(p_promotion_code,''))), '');
  subtotal NUMERIC(10,2);
  addons NUMERIC(10,2) := 0;
  fee NUMERIC(10,2);
  discount NUMERIC(10,2) := 0;
BEGIN
  IF u IS NULL THEN RAISE EXCEPTION 'Sign in to check offers' USING ERRCODE = '42501'; END IF;
  IF p_quantity IS NULL OR p_quantity NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'Quantity must be between 1 and 20' USING ERRCODE = '22023'; END IF;
  IF p_customizations IS NULL OR jsonb_typeof(p_customizations) <> 'array' OR jsonb_array_length(p_customizations) > 20 THEN RAISE EXCEPTION 'Invalid add-ons' USING ERRCODE = '22023'; END IF;
  SELECT * INTO meal FROM public.meals WHERE id = p_meal_id AND is_active;
  IF NOT FOUND OR meal.meal_type NOT IN (p_meal_type,'both') THEN RAISE EXCEPTION 'This meal is unavailable'; END IF;
  SELECT * INTO menu_day FROM public.menu_days WHERE menu_date = p_order_date AND is_published;
  IF NOT FOUND THEN RAISE EXCEPTION 'The menu for this day has not been published'; END IF;
  SELECT * INTO menu_item FROM public.menu_items WHERE menu_day_id = menu_day.id AND meal_id = meal.id AND availability;
  IF NOT FOUND OR NOT p_meal_type = ANY(menu_item.service_meal_types) THEN RAISE EXCEPTION 'This meal is not available for the selected service'; END IF;
  SELECT * INTO address FROM public.addresses WHERE id = p_address_id AND user_id = u;
  IF NOT FOUND THEN RAISE EXCEPTION 'Choose a saved address belonging to your account'; END IF;
  SELECT * INTO zone FROM public.delivery_zones
  WHERE id = private.resolve_delivery_zone_v2(address.latitude,address.longitude,address.pincode,address.area,address.sector,p_meal_type)
    AND status = 'available';
  IF NOT FOUND OR NOT address.is_serviceable OR zone.id IS DISTINCT FROM address.zone_id THEN RAISE EXCEPTION 'This address is outside current delivery coverage'; END IF;
  subtotal := meal.base_price * p_quantity;
  FOR entry IN SELECT value FROM jsonb_array_elements(p_customizations) LOOP
    IF jsonb_typeof(entry) <> 'object' OR coalesce(entry->>'customization_id','') !~ '^[0-9a-fA-F-]{36}$' OR coalesce(entry->>'quantity','') !~ '^[0-9]{1,3}$' THEN RAISE EXCEPTION 'Invalid add-on'; END IF;
    SELECT * INTO customization FROM public.meal_customizations WHERE id = (entry->>'customization_id')::UUID AND is_active;
    IF NOT FOUND OR (customization.meal_id IS NOT NULL AND customization.meal_id <> meal.id) THEN RAISE EXCEPTION 'An add-on is unavailable for this meal'; END IF;
    addons := addons + customization.price * (entry->>'quantity')::INTEGER;
  END LOOP;
  IF subtotal + addons < zone.min_order_amount THEN RAISE EXCEPTION 'Minimum order amount for this zone is %', zone.min_order_amount; END IF;
  fee := CASE WHEN zone.is_free_delivery THEN 0 ELSE zone.delivery_fee END;

  FOR campaign IN
    SELECT * FROM private.promotion_campaigns c
    WHERE c.is_active AND clock_timestamp() >= c.starts_at AND clock_timestamp() < c.ends_at
    ORDER BY c.created_at DESC
  LOOP
    evaluation := private.promotion_evaluation(campaign.id,u,p_order_date,p_meal_type,zone.id,meal.id,subtotal+addons,clock_timestamp(),false);
    IF (evaluation->>'eligible')::BOOLEAN THEN available := available || jsonb_build_array(evaluation); END IF;
  END LOOP;

  IF normalized_code IS NOT NULL THEN
    SELECT * INTO campaign FROM private.promotion_campaigns WHERE code = normalized_code;
    IF NOT FOUND THEN RAISE EXCEPTION 'Offer code not found'; END IF;
    applied := private.promotion_evaluation(campaign.id,u,p_order_date,p_meal_type,zone.id,meal.id,subtotal+addons,clock_timestamp(),false);
    IF NOT (applied->>'eligible')::BOOLEAN THEN RAISE EXCEPTION '%', applied->>'reason'; END IF;
    discount := (applied->>'discount_amount')::NUMERIC;
  END IF;

  RETURN jsonb_build_object(
    'meals_subtotal',subtotal,'addons_total',addons,'delivery_fee',fee,
    'discount',discount,'grand_total',subtotal+addons+fee-discount,
    'applied_offer',applied,'available_offers',available
  );
END;
$$;

CREATE OR REPLACE FUNCTION private.promotion_management_document()
RETURNS JSONB LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT jsonb_build_object(
    'campaigns', coalesce((SELECT jsonb_agg(to_jsonb(c) || jsonb_build_object(
      'redemption_count',(SELECT count(*) FROM private.promotion_redemptions r WHERE r.promotion_id=c.id),
      'spent',(SELECT coalesce(sum(r.discount_amount),0) FROM private.promotion_redemptions r WHERE r.promotion_id=c.id)
    ) ORDER BY c.created_at DESC) FROM private.promotion_campaigns c),'[]'::JSONB),
    'meals', coalesce((SELECT jsonb_agg(jsonb_build_object('id',m.id,'name',m.name,'meal_type',m.meal_type,'is_active',m.is_active) ORDER BY m.name) FROM public.meals m),'[]'::JSONB),
    'areas', coalesce((SELECT jsonb_agg(jsonb_build_object('id',z.id,'name',z.name,'status',z.status) ORDER BY z.name) FROM public.delivery_zones z WHERE z.boundary IS NOT NULL),'[]'::JSONB)
  );
$$;

CREATE OR REPLACE FUNCTION public.get_promotion_management()
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  PERFORM private.require_admin_access();
  RETURN private.promotion_management_document();
END;
$$;

CREATE OR REPLACE FUNCTION public.save_promotion_campaign(
  p_id UUID,
  p_code TEXT,
  p_name TEXT,
  p_description TEXT,
  p_discount_type TEXT,
  p_discount_value NUMERIC,
  p_minimum_subtotal NUMERIC,
  p_maximum_discount NUMERIC,
  p_total_budget NUMERIC,
  p_starts_at TIMESTAMPTZ,
  p_ends_at TIMESTAMPTZ,
  p_service_date_start DATE,
  p_service_date_end DATE,
  p_is_active BOOLEAN,
  p_first_order_only BOOLEAN,
  p_per_user_limit INTEGER,
  p_eligible_meal_types TEXT[],
  p_eligible_meal_ids UUID[],
  p_eligible_zone_ids TEXT[]
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  actor UUID := private.require_admin_access();
  target UUID := coalesce(p_id,gen_random_uuid());
  normalized_code TEXT := upper(btrim(coalesce(p_code,'')));
  action_name TEXT;
BEGIN
  IF normalized_code !~ '^[A-Z0-9][A-Z0-9_-]{2,29}$' OR length(btrim(coalesce(p_name,''))) NOT BETWEEN 2 AND 80 OR length(coalesce(p_description,'')) > 240 THEN RAISE EXCEPTION 'Check the offer code, name and description' USING ERRCODE='22023'; END IF;
  IF p_discount_type NOT IN ('fixed','percentage') OR p_discount_value <= 0 OR (p_discount_type='percentage' AND p_discount_value>100) THEN RAISE EXCEPTION 'Check the discount value' USING ERRCODE='22023'; END IF;
  IF p_minimum_subtotal < 0 OR (p_maximum_discount IS NOT NULL AND p_maximum_discount<=0) OR (p_total_budget IS NOT NULL AND p_total_budget<=0) OR p_per_user_limit NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'Check the offer limits' USING ERRCODE='22023'; END IF;
  IF p_discount_type='fixed' AND p_total_budget IS NOT NULL AND p_total_budget<least(p_discount_value,coalesce(p_maximum_discount,p_discount_value)) THEN RAISE EXCEPTION 'Campaign budget is lower than one redemption' USING ERRCODE='22023'; END IF;
  IF p_starts_at IS NULL OR p_ends_at IS NULL OR p_ends_at<=p_starts_at OR (p_service_date_start IS NOT NULL AND p_service_date_end IS NOT NULL AND p_service_date_end<p_service_date_start) THEN RAISE EXCEPTION 'Check the offer dates' USING ERRCODE='22023'; END IF;
  IF cardinality(coalesce(p_eligible_meal_types,ARRAY[]::TEXT[]))=0 OR NOT coalesce(p_eligible_meal_types,ARRAY[]::TEXT[]) <@ ARRAY['breakfast','lunch','dinner']::TEXT[] THEN RAISE EXCEPTION 'Choose at least one meal service' USING ERRCODE='22023'; END IF;
  IF p_is_active AND p_ends_at<=clock_timestamp() THEN RAISE EXCEPTION 'An expired offer cannot be activated' USING ERRCODE='22023'; END IF;
  IF EXISTS (SELECT 1 FROM unnest(coalesce(p_eligible_meal_ids,ARRAY[]::UUID[])) AS candidate(id) LEFT JOIN public.meals m ON m.id=candidate.id WHERE m.id IS NULL) THEN RAISE EXCEPTION 'An eligible meal no longer exists'; END IF;
  IF EXISTS (SELECT 1 FROM unnest(coalesce(p_eligible_zone_ids,ARRAY[]::TEXT[])) AS candidate(id) LEFT JOIN public.delivery_zones z ON z.id=candidate.id WHERE z.id IS NULL) THEN RAISE EXCEPTION 'An eligible delivery area no longer exists'; END IF;

  IF p_id IS NULL THEN
    INSERT INTO private.promotion_campaigns(id,code,name,description,discount_type,discount_value,minimum_subtotal,maximum_discount,total_budget,starts_at,ends_at,service_date_start,service_date_end,is_active,first_order_only,per_user_limit,eligible_meal_types,eligible_meal_ids,eligible_zone_ids,created_by,updated_by)
    VALUES(target,normalized_code,btrim(p_name),btrim(coalesce(p_description,'')),p_discount_type,p_discount_value,p_minimum_subtotal,p_maximum_discount,p_total_budget,p_starts_at,p_ends_at,p_service_date_start,p_service_date_end,p_is_active,p_first_order_only,p_per_user_limit,p_eligible_meal_types,coalesce(p_eligible_meal_ids,ARRAY[]::UUID[]),coalesce(p_eligible_zone_ids,ARRAY[]::TEXT[]),actor,actor);
    action_name := 'created';
  ELSE
    IF p_total_budget IS NOT NULL AND p_total_budget < (SELECT coalesce(sum(discount_amount),0) FROM private.promotion_redemptions WHERE promotion_id=p_id) THEN RAISE EXCEPTION 'Campaign budget cannot be lower than discount already spent' USING ERRCODE='23514'; END IF;
    UPDATE private.promotion_campaigns SET code=normalized_code,name=btrim(p_name),description=btrim(coalesce(p_description,'')),discount_type=p_discount_type,discount_value=p_discount_value,minimum_subtotal=p_minimum_subtotal,maximum_discount=p_maximum_discount,total_budget=p_total_budget,starts_at=p_starts_at,ends_at=p_ends_at,service_date_start=p_service_date_start,service_date_end=p_service_date_end,is_active=p_is_active,first_order_only=p_first_order_only,per_user_limit=p_per_user_limit,eligible_meal_types=p_eligible_meal_types,eligible_meal_ids=coalesce(p_eligible_meal_ids,ARRAY[]::UUID[]),eligible_zone_ids=coalesce(p_eligible_zone_ids,ARRAY[]::TEXT[]),updated_by=actor,updated_at=clock_timestamp()
    WHERE id=p_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Offer not found' USING ERRCODE='P0002'; END IF;
    action_name := 'updated';
  END IF;
  INSERT INTO private.promotion_events(promotion_id,actor_id,action,snapshot) SELECT target,actor,action_name,to_jsonb(c) FROM private.promotion_campaigns c WHERE c.id=target;
  RETURN private.promotion_management_document();
END;
$$;

CREATE OR REPLACE FUNCTION public.set_promotion_campaign_active(p_id UUID,p_is_active BOOLEAN)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor UUID := private.require_admin_access(); snapshot JSONB; campaign private.promotion_campaigns%ROWTYPE; spent NUMERIC(12,2);
BEGIN
  SELECT * INTO campaign FROM private.promotion_campaigns WHERE id=p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Offer not found' USING ERRCODE='P0002'; END IF;
  IF p_is_active AND campaign.ends_at<=clock_timestamp() THEN RAISE EXCEPTION 'An expired offer cannot be activated' USING ERRCODE='22023'; END IF;
  SELECT coalesce(sum(discount_amount),0) INTO spent FROM private.promotion_redemptions WHERE promotion_id=p_id;
  IF p_is_active AND campaign.total_budget IS NOT NULL AND spent>=campaign.total_budget THEN RAISE EXCEPTION 'This campaign budget is already exhausted' USING ERRCODE='23514'; END IF;
  UPDATE private.promotion_campaigns AS c SET is_active=p_is_active,updated_by=actor,updated_at=clock_timestamp() WHERE c.id=p_id RETURNING to_jsonb(c) INTO snapshot;
  INSERT INTO private.promotion_events(promotion_id,actor_id,action,snapshot) VALUES(p_id,actor,CASE WHEN p_is_active THEN 'activated' ELSE 'paused' END,snapshot);
  RETURN private.promotion_management_document();
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_unused_promotion_campaign(p_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor UUID := private.require_admin_access(); snapshot JSONB;
BEGIN
  IF EXISTS (SELECT 1 FROM private.promotion_redemptions WHERE promotion_id=p_id) THEN RAISE EXCEPTION 'Used offers must be paused, not deleted' USING ERRCODE='23503'; END IF;
  DELETE FROM private.promotion_campaigns AS c WHERE c.id=p_id RETURNING to_jsonb(c) INTO snapshot;
  IF NOT FOUND THEN RAISE EXCEPTION 'Offer not found' USING ERRCODE='P0002'; END IF;
  INSERT INTO private.promotion_events(promotion_id,actor_id,action,snapshot) VALUES(p_id,actor,'deleted',snapshot);
  RETURN private.promotion_management_document();
END;
$$;

-- Replace checkout with a promotion-aware signature while preserving all existing
-- menu, cutoff, capacity, serviceability, idempotency and snapshot guarantees.
DROP FUNCTION public.place_order_secure(DATE,TEXT,UUID,UUID,UUID,INT,JSONB,TEXT,UUID,JSONB);
CREATE FUNCTION public.place_order_secure(
 p_order_date DATE,p_meal_type TEXT,p_delivery_slot_id UUID,p_address_id UUID,p_meal_id UUID,p_quantity INT,
 p_customizations JSONB DEFAULT '[]',p_notes TEXT DEFAULT NULL,p_idempotency_key UUID DEFAULT NULL,p_preferences JSONB DEFAULT '{}',p_promotion_code TEXT DEFAULT NULL
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
 u UUID := auth.uid(); m public.meals%ROWTYPE; md public.menu_days%ROWTYPE; mi public.menu_items%ROWTYPE;
 s public.delivery_slots%ROWTYPE; a public.addresses%ROWTYPE; z public.delivery_zones%ROWTYPE;
 c public.meal_customizations%ROWTYPE; e JSONB; extras JSONB := '[]'; normalized JSONB; payload JSONB; existing public.orders%ROWTYPE;
 preferences JSONB; cid UUID; qty INT; booked BIGINT; subtotal NUMERIC(10,2); addons NUMERIC(10,2):=0;
 fee NUMERIC(10,2); oid UUID := gen_random_uuid(); iid UUID; snapshot JSONB; normalized_code TEXT := nullif(upper(btrim(coalesce(p_promotion_code,''))),'');
 promo_id UUID; promo JSONB; promo_name TEXT; discount NUMERIC(10,2):=0;
BEGIN
 IF u IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
 IF p_idempotency_key IS NULL THEN RAISE EXCEPTION 'A checkout request key is required'; END IF;
 IF p_quantity IS NULL OR p_quantity NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'Quantity must be between 1 and 20'; END IF;
 IF p_customizations IS NULL OR jsonb_typeof(p_customizations) <> 'array' THEN RAISE EXCEPTION 'Add-ons must be an array'; END IF;
 IF jsonb_array_length(p_customizations)>20 THEN RAISE EXCEPTION 'Too many add-ons'; END IF;
 FOR e IN SELECT value FROM jsonb_array_elements(p_customizations) LOOP
   IF jsonb_typeof(e)<>'object' OR e->>'customization_id' IS NULL OR coalesce(e->>'quantity','') !~ '^[0-9]{1,3}$' THEN RAISE EXCEPTION 'Invalid add-on'; END IF;
   cid := (e->>'customization_id')::uuid; qty := (e->>'quantity')::int;
   IF qty NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'Add-on quantity must be between 1 and 100'; END IF;
   extras := extras || jsonb_build_array(jsonb_build_object('customization_id',cid,'quantity',qty));
 END LOOP;
 IF EXISTS (SELECT 1 FROM jsonb_array_elements(extras) v GROUP BY v->>'customization_id' HAVING count(*)>1) THEN RAISE EXCEPTION 'Duplicate add-on'; END IF;
 SELECT coalesce(jsonb_agg(value ORDER BY value->>'customization_id'),'[]') INTO normalized FROM jsonb_array_elements(extras);
 IF p_preferences IS NULL OR jsonb_typeof(p_preferences)<>'object' THEN RAISE EXCEPTION 'Invalid preparation preferences'; END IF;
 IF coalesce(p_preferences->>'spiceLevel','Regular') NOT IN ('Regular','Less Spicy') OR coalesce(p_preferences->>'oilLevel','Standard') NOT IN ('Standard','Less Oil (Fit)') THEN RAISE EXCEPTION 'Invalid preparation preference'; END IF;
 IF length(coalesce(p_notes,''))>1000 THEN RAISE EXCEPTION 'Notes must be at most 1000 characters'; END IF;
 payload := jsonb_build_object('date',p_order_date,'type',p_meal_type,'slot',p_delivery_slot_id,'address',p_address_id,'meal',p_meal_id,'quantity',p_quantity,'addons',normalized,'notes',nullif(btrim(p_notes),''),'preferences',p_preferences,'promotion_code',normalized_code);
 PERFORM pg_advisory_xact_lock(hashtextextended(u::text||p_idempotency_key::text,0));
 SELECT * INTO existing FROM public.orders WHERE user_id=u AND idempotency_key=p_idempotency_key;
 IF FOUND THEN
   IF existing.request_payload IS DISTINCT FROM payload THEN RAISE EXCEPTION 'This request key belongs to different order details'; END IF;
   RETURN private.order_document(existing.id);
 END IF;
 SELECT * INTO s FROM public.delivery_slots WHERE id=p_delivery_slot_id FOR UPDATE;
 IF NOT FOUND OR NOT s.is_active OR s.meal_type IS DISTINCT FROM p_meal_type THEN RAISE EXCEPTION 'Choose an active delivery slot for this meal'; END IF;
 PERFORM private.assert_order_window(p_order_date,p_meal_type,clock_timestamp());
 SELECT * INTO m FROM public.meals WHERE id=p_meal_id FOR SHARE;
 IF NOT FOUND OR NOT m.is_active OR m.meal_type NOT IN (p_meal_type,'both') THEN RAISE EXCEPTION 'This meal is unavailable'; END IF;
 SELECT * INTO md FROM public.menu_days WHERE menu_date=p_order_date FOR SHARE;
 IF NOT FOUND OR NOT md.is_published THEN RAISE EXCEPTION 'The menu for this day has not been published'; END IF;
 SELECT * INTO mi FROM public.menu_items WHERE menu_day_id=md.id AND meal_id=m.id FOR SHARE;
 IF NOT FOUND OR NOT mi.availability OR NOT p_meal_type=ANY(mi.service_meal_types) THEN RAISE EXCEPTION 'This meal is not available in the selected menu service'; END IF;
 SELECT coalesce(sum(i.quantity),0) INTO booked FROM public.orders o JOIN public.order_items i ON i.order_id=o.id WHERE o.delivery_slot_id=s.id AND o.order_date=p_order_date AND o.status<>'cancelled';
 IF booked+p_quantity>s.max_orders THEN RAISE EXCEPTION 'This delivery slot has insufficient remaining portions'; END IF;
 SELECT * INTO a FROM public.addresses WHERE id=p_address_id AND user_id=u FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Choose a saved address belonging to your account'; END IF;
 SELECT * INTO z FROM public.delivery_zones WHERE id=private.resolve_delivery_zone_v2(a.latitude,a.longitude,a.pincode,a.area,a.sector,p_meal_type) AND status='available' FOR SHARE;
 IF NOT FOUND OR NOT a.is_serviceable OR z.id IS DISTINCT FROM a.zone_id THEN RAISE EXCEPTION 'This address is outside current delivery coverage'; END IF;
 fee := CASE WHEN z.is_free_delivery THEN 0 ELSE z.delivery_fee END;
 subtotal := m.base_price*p_quantity;
 FOR e IN SELECT value FROM jsonb_array_elements(normalized) LOOP
   SELECT * INTO c FROM public.meal_customizations WHERE id=(e->>'customization_id')::uuid FOR SHARE;
   IF NOT FOUND OR NOT c.is_active OR (c.meal_id IS NOT NULL AND c.meal_id<>m.id) THEN RAISE EXCEPTION 'An add-on is unavailable for this meal'; END IF;
   addons := addons+c.price*(e->>'quantity')::int;
 END LOOP;
 IF subtotal+addons<z.min_order_amount THEN RAISE EXCEPTION 'Minimum order amount for this zone is %',z.min_order_amount; END IF;
 IF normalized_code IS NOT NULL THEN
   SELECT id,name INTO promo_id,promo_name FROM private.promotion_campaigns WHERE code=normalized_code;
   IF NOT FOUND THEN RAISE EXCEPTION 'Offer code not found'; END IF;
   promo := private.promotion_evaluation(promo_id,u,p_order_date,p_meal_type,z.id,m.id,subtotal+addons,clock_timestamp(),true);
   IF NOT (promo->>'eligible')::BOOLEAN THEN RAISE EXCEPTION '%',promo->>'reason'; END IF;
   discount := (promo->>'discount_amount')::NUMERIC;
 END IF;
 preferences := jsonb_build_object('spiceLevel',coalesce(p_preferences->>'spiceLevel','Regular'),'oilLevel',coalesce(p_preferences->>'oilLevel','Standard'),'dietType',m.diet_type);
 snapshot := to_jsonb(a) || jsonb_build_object('zoneId',z.id,'deliveryFee',fee,'slotLabel',s.start_time::text||' – '||s.end_time::text,'capturedAt',clock_timestamp());
 INSERT INTO public.orders(id,user_id,address_id,order_number,idempotency_key,request_payload,order_date,meal_type,delivery_slot_id,status,subtotal,customization_total,delivery_fee,discount,grand_total,payment_status,notes,address_snapshot,promotion_id,promotion_code_snapshot,promotion_name_snapshot)
 VALUES(oid,u,a.id,'THA-'||to_char(p_order_date,'YYYYMMDD')||'-'||replace(oid::text,'-',''),p_idempotency_key,payload,p_order_date,p_meal_type,s.id,'confirmed',subtotal,addons,fee,discount,subtotal+addons+fee-discount,'pending',nullif(btrim(p_notes),''),snapshot,promo_id,normalized_code,promo_name);
 INSERT INTO public.order_items(order_id,meal_id,meal_name_snapshot,preparation_preferences,quantity,unit_price,line_total) VALUES(oid,m.id,m.name,preferences,p_quantity,m.base_price,subtotal) RETURNING id INTO iid;
 FOR e IN SELECT value FROM jsonb_array_elements(normalized) LOOP
   SELECT * INTO c FROM public.meal_customizations WHERE id=(e->>'customization_id')::uuid;
   INSERT INTO public.order_customizations(order_item_id,customization_id,customization_name_snapshot,quantity,unit_price,line_total) VALUES(iid,c.id,c.name,(e->>'quantity')::int,c.price,c.price*(e->>'quantity')::int);
 END LOOP;
 IF promo_id IS NOT NULL THEN INSERT INTO private.promotion_redemptions(promotion_id,order_id,user_id,discount_amount) VALUES(promo_id,oid,u,discount); END IF;
 RETURN private.order_document(oid);
END;
$$;

REVOKE ALL ON TABLE private.promotion_campaigns,private.promotion_redemptions,private.promotion_events FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION private.promotion_evaluation(UUID,UUID,DATE,TEXT,TEXT,UUID,NUMERIC,TIMESTAMPTZ,BOOLEAN),private.promotion_management_document() FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.get_order_promotion_quote(DATE,TEXT,UUID,UUID,INTEGER,JSONB,TEXT),public.get_promotion_management(),public.save_promotion_campaign(UUID,TEXT,TEXT,TEXT,TEXT,NUMERIC,NUMERIC,NUMERIC,NUMERIC,TIMESTAMPTZ,TIMESTAMPTZ,DATE,DATE,BOOLEAN,BOOLEAN,INTEGER,TEXT[],UUID[],TEXT[]),public.set_promotion_campaign_active(UUID,BOOLEAN),public.delete_unused_promotion_campaign(UUID),public.place_order_secure(DATE,TEXT,UUID,UUID,UUID,INT,JSONB,TEXT,UUID,JSONB,TEXT) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.get_order_promotion_quote(DATE,TEXT,UUID,UUID,INTEGER,JSONB,TEXT),public.get_promotion_management(),public.save_promotion_campaign(UUID,TEXT,TEXT,TEXT,TEXT,NUMERIC,NUMERIC,NUMERIC,NUMERIC,TIMESTAMPTZ,TIMESTAMPTZ,DATE,DATE,BOOLEAN,BOOLEAN,INTEGER,TEXT[],UUID[],TEXT[]),public.set_promotion_campaign_active(UUID,BOOLEAN),public.delete_unused_promotion_campaign(UUID),public.place_order_secure(DATE,TEXT,UUID,UUID,UUID,INT,JSONB,TEXT,UUID,JSONB,TEXT) TO authenticated;

COMMENT ON TABLE private.promotion_campaigns IS 'Private admin-managed promotion rules; Customers use guarded quote and checkout RPCs.';
COMMENT ON TABLE private.promotion_redemptions IS 'Immutable promotion use ledger. Cancellation does not silently restore an offer.';
COMMENT ON FUNCTION public.get_order_promotion_quote(DATE,TEXT,UUID,UUID,INTEGER,JSONB,TEXT) IS 'Authenticated public-safe promotion quote calculated from authoritative menu, add-on, address and campaign data.';

-- Inactive starter configuration: review unit economics before activation.
INSERT INTO private.promotion_campaigns(code,name,description,discount_type,discount_value,minimum_subtotal,maximum_discount,total_budget,starts_at,ends_at,is_active,first_order_only,per_user_limit,created_by,updated_by)
SELECT 'WELCOME40','Welcome to Thalimitra','₹40 off your first eligible order of ₹249 or more.','fixed',40,249,40,4000,clock_timestamp(),clock_timestamp()+interval '180 days',false,true,1,u.id,u.id
FROM auth.users u JOIN public.user_roles r ON r.user_id=u.id AND r.role='admin'
ORDER BY r.created_at LIMIT 1
ON CONFLICT(code) DO NOTHING;
